version: "3"
services:
  restapi:
    build: .
    ports:
      - "5000:4567"
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "restapi"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
